name: intro_slider_example
description: Demonstrates how to use the intro_slider plugin.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  intro_slider:
    path: ../


flutter:

  uses-material-design: true

  assets:
    - images/photo_eraser.png
    - images/photo_pencil.png
    - images/photo_ruler.png
    - images/photo_school.png
    - images/photo_museum.png
    - images/photo_coffee_shop.png


  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf