name: intro_slider
description: A plugin to help you make intro slider screen to show the major features of your app. You can change the image, button, text style, color, and more things
authors:
  - Duy Tran <tranquangduy7994@gmail.com>
homepage: https://github.com/duytq94/flutter-intro-slider
version: 1.1.6

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
          sdk: flutter

flutter:
  plugin:
    androidPackage: com.dfa.introslider
    pluginClass: IntroSliderPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"